package Form;


import Form.BaoCao;
import Form.Dashboard;
import Form.HoaDon;
import Form.KhachHang;
import Form.NCC;
import Form.SanPham;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bùi Tuấn
 */
public class Home extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor;
    public Home() {
        initComponents();
        DefaultColor = new Color(22,67,108);
        ClickedColor = new Color(40, 117, 148);
        
        jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(DefaultColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(DefaultColor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPSanpham = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPHoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPNcc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPKhachHang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPNhaVien = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPBaoCao = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Namebutton = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 67, 108));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/smart-tv.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("F_Store");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 26, 100, 110));

        jPDashboard.setBackground(new java.awt.Color(22, 67, 108));
        jPDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPDashboardMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard.png"))); // NOI18N
        jLabel4.setText("Dashboard");

        javax.swing.GroupLayout jPDashboardLayout = new javax.swing.GroupLayout(jPDashboard);
        jPDashboard.setLayout(jPDashboardLayout);
        jPDashboardLayout.setHorizontalGroup(
            jPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDashboardLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPDashboardLayout.setVerticalGroup(
            jPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.add(jPDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        jPSanpham.setBackground(new java.awt.Color(22, 67, 108));
        jPSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPSanphamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPSanphamMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product.png"))); // NOI18N
        jLabel5.setText("Quản lý sản phẩm ");

        javax.swing.GroupLayout jPSanphamLayout = new javax.swing.GroupLayout(jPSanpham);
        jPSanpham.setLayout(jPSanphamLayout);
        jPSanphamLayout.setHorizontalGroup(
            jPSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSanphamLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPSanphamLayout.setVerticalGroup(
            jPSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPSanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPHoaDon.setBackground(new java.awt.Color(22, 67, 108));
        jPHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPHoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPHoaDonMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        jLabel7.setText("Quản lý hóa đơn ");

        javax.swing.GroupLayout jPHoaDonLayout = new javax.swing.GroupLayout(jPHoaDon);
        jPHoaDon.setLayout(jPHoaDonLayout);
        jPHoaDonLayout.setHorizontalGroup(
            jPHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHoaDonLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPHoaDonLayout.setVerticalGroup(
            jPHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jPNcc.setBackground(new java.awt.Color(22, 67, 108));
        jPNcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPNccMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPNccMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/manufacture.png"))); // NOI18N
        jLabel9.setText("Quản lý nhà cung cấp");

        javax.swing.GroupLayout jPNccLayout = new javax.swing.GroupLayout(jPNcc);
        jPNcc.setLayout(jPNccLayout);
        jPNccLayout.setHorizontalGroup(
            jPNccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNccLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel9)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPNccLayout.setVerticalGroup(
            jPNccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPNcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        jPKhachHang.setBackground(new java.awt.Color(22, 67, 108));
        jPKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPKhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPKhachHangMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user.png"))); // NOI18N
        jLabel10.setText("Quản lý khách hàng ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPKhachHangLayout = new javax.swing.GroupLayout(jPKhachHang);
        jPKhachHang.setLayout(jPKhachHangLayout);
        jPKhachHangLayout.setHorizontalGroup(
            jPKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKhachHangLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel10)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPKhachHangLayout.setVerticalGroup(
            jPKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        jPNhaVien.setBackground(new java.awt.Color(22, 67, 108));
        jPNhaVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPNhaVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPNhaVienMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out.png"))); // NOI18N
        jLabel11.setText("Đăng xuất");

        javax.swing.GroupLayout jPNhaVienLayout = new javax.swing.GroupLayout(jPNhaVien);
        jPNhaVien.setLayout(jPNhaVienLayout);
        jPNhaVienLayout.setHorizontalGroup(
            jPNhaVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNhaVienLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPNhaVienLayout.setVerticalGroup(
            jPNhaVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNhaVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPNhaVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 200, -1));

        jPBaoCao.setBackground(new java.awt.Color(22, 67, 108));
        jPBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBaoCaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPBaoCaoMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jLabel12.setText("Báo cáo");

        javax.swing.GroupLayout jPBaoCaoLayout = new javax.swing.GroupLayout(jPBaoCao);
        jPBaoCao.setLayout(jPBaoCaoLayout);
        jPBaoCaoLayout.setHorizontalGroup(
            jPBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBaoCaoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel12)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPBaoCaoLayout.setVerticalGroup(
            jPBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBaoCaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 290, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 740));

        jPanel3.setBackground(new java.awt.Color(135, 210, 243));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        Namebutton.setBackground(new java.awt.Color(255, 255, 255));
        Namebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Namebutton.setForeground(new java.awt.Color(51, 51, 51));
        Namebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Namebutton.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Namebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Namebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1020, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dashboard");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 1020, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDashboardMousePressed
       jPDashboard.setBackground(ClickedColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(DefaultColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(DefaultColor);
        Namebutton.setText("Dashboard");
    }//GEN-LAST:event_jPDashboardMousePressed

    private void jPSanphamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSanphamMousePressed
        jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(DefaultColor);
        jPSanpham.setBackground(ClickedColor);
        jPBaoCao.setBackground(DefaultColor);
        Namebutton.setText("Quản Lý Sản Phẩm");
    }//GEN-LAST:event_jPSanphamMousePressed

    private void jPHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHoaDonMousePressed
        jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(ClickedColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(DefaultColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(DefaultColor);
        Namebutton.setText("Quản Lý Hóa Đơn");

    }//GEN-LAST:event_jPHoaDonMousePressed

    private void jPNccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNccMousePressed
        jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(ClickedColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(DefaultColor);
        Namebutton.setText("Quản lý nhà cung cấp");
    }//GEN-LAST:event_jPNccMousePressed

    private void jPKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPKhachHangMousePressed
       jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(ClickedColor);
        jPNcc.setBackground(DefaultColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(DefaultColor);
        Namebutton.setText("Quản lý Khách Hàng");
    }//GEN-LAST:event_jPKhachHangMousePressed

    private void jPNhaVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNhaVienMousePressed
        System.exit(0);
    }//GEN-LAST:event_jPNhaVienMousePressed

    private void jPDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDashboardMouseClicked
        Dashboard dashboard = new Dashboard();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(dashboard).setVisible(true);
        
    }//GEN-LAST:event_jPDashboardMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPKhachHangMouseClicked
        KhachHang khachHang = new KhachHang();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(khachHang).setVisible(true);
    }//GEN-LAST:event_jPKhachHangMouseClicked

    private void jPNhaVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNhaVienMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPNhaVienMouseClicked

    private void jPNccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNccMouseClicked
        NCC ncc = new NCC();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(ncc).setVisible(true);
    }//GEN-LAST:event_jPNccMouseClicked

    private void jPHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHoaDonMouseClicked
        HoaDon hoadon = new  HoaDon();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(hoadon).setVisible(true);
    }//GEN-LAST:event_jPHoaDonMouseClicked

    private void jPSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSanphamMouseClicked
        SanPham sanpham = new SanPham();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(sanpham).setVisible(true);
    }//GEN-LAST:event_jPSanphamMouseClicked

    private void jPBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBaoCaoMouseClicked
        BaoCao baoCao = new BaoCao();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(baoCao).setVisible(true);
    }//GEN-LAST:event_jPBaoCaoMouseClicked

    private void jPBaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBaoCaoMousePressed
        jPDashboard.setBackground(DefaultColor);
        jPHoaDon.setBackground(DefaultColor);
        jPKhachHang.setBackground(DefaultColor);
        jPNcc.setBackground(DefaultColor);
        jPNhaVien.setBackground(DefaultColor);
        jPSanpham.setBackground(DefaultColor);
        jPBaoCao.setBackground(ClickedColor);
        Namebutton.setText("Báo Cáo");
    }//GEN-LAST:event_jPBaoCaoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namebutton;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBaoCao;
    private javax.swing.JPanel jPDashboard;
    private javax.swing.JPanel jPHoaDon;
    private javax.swing.JPanel jPKhachHang;
    private javax.swing.JPanel jPNcc;
    private javax.swing.JPanel jPNhaVien;
    private javax.swing.JPanel jPSanpham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
