/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import static Form.KhachHang.ClearText;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bùi Tuấn
 */
public class NCC extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    public NCC() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);        
        Showdata();
        setJtextField(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTNCC = new javax.swing.JTabbedPane();
        jPAddSanpham = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddressBrand = new javax.swing.JTextField();
        txtNameBrand = new javax.swing.JTextField();
        txtPhoneBrand = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPQlSanpham = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNCC = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtSearchNCC = new javax.swing.JTextField();
        jButtonSearcn = new javax.swing.JLabel();
        jPOptionsSanpham = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNameBrand1 = new javax.swing.JTextField();
        txtAddressBrand1 = new javax.swing.JTextField();
        txtPhoneBrand1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonChange = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1020, 710));

        jTNCC.setBackground(new java.awt.Color(255, 255, 255));
        jTNCC.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTNCC.setOpaque(true);

        jPAddSanpham.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(22, 67, 108));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-button.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Brand");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jButtonAdd.setBackground(new java.awt.Color(22, 67, 108));
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-button (1).png"))); // NOI18N
        jLabel8.setText("Add");

        javax.swing.GroupLayout jButtonAddLayout = new javax.swing.GroupLayout(jButtonAdd);
        jButtonAdd.setLayout(jButtonAddLayout);
        jButtonAddLayout.setHorizontalGroup(
            jButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonAddLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jButtonAddLayout.setVerticalGroup(
            jButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tên nhà cung cấp :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Số điện thoại :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Địa Chỉ :");

        javax.swing.GroupLayout jPAddSanphamLayout = new javax.swing.GroupLayout(jPAddSanpham);
        jPAddSanpham.setLayout(jPAddSanphamLayout);
        jPAddSanphamLayout.setHorizontalGroup(
            jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPAddSanphamLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAddSanphamLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPAddSanphamLayout.createSequentialGroup()
                        .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtPhoneBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(107, 107, 107))))
            .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPAddSanphamLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(txtNameBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(578, Short.MAX_VALUE)))
        );
        jPAddSanphamLayout.setVerticalGroup(
            jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddSanphamLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddressBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(jPAddSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPAddSanphamLayout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(txtNameBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );

        jTNCC.addTab("Thêm nhà cung cấp ", jPAddSanpham);

        jPQlSanpham.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(22, 67, 108));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/manage.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Brand");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(683, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        TableNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên nhà cung cấp ", "Địa chỉ ", "Số điện thoại "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableNCC.setRowHeight(35);
        TableNCC.setSelectionBackground(new java.awt.Color(22, 67, 108));
        TableNCC.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TableNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableNCC);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Thông tin nhà cung cấp :");

        jButtonSearcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButtonSearcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSearcnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPQlSanphamLayout = new javax.swing.GroupLayout(jPQlSanpham);
        jPQlSanpham.setLayout(jPQlSanphamLayout);
        jPQlSanphamLayout.setHorizontalGroup(
            jPQlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPQlSanphamLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPQlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPQlSanphamLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearcn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPQlSanphamLayout.setVerticalGroup(
            jPQlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPQlSanphamLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPQlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPQlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSearcn))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        jTNCC.addTab("Quản lý nhà cung cấp ", jPQlSanpham);

        jPOptionsSanpham.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(22, 67, 108));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orther.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Other");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        txtAddressBrand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressBrand1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("ID");

        jButtonChange.setBackground(new java.awt.Color(22, 67, 108));
        jButtonChange.setPreferredSize(new java.awt.Dimension(185, 45));
        jButtonChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonChangeMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/change.png"))); // NOI18N
        jLabel15.setText("Change");

        javax.swing.GroupLayout jButtonChangeLayout = new javax.swing.GroupLayout(jButtonChange);
        jButtonChange.setLayout(jButtonChangeLayout);
        jButtonChangeLayout.setHorizontalGroup(
            jButtonChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonChangeLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(49, 49, 49))
        );
        jButtonChangeLayout.setVerticalGroup(
            jButtonChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonDelete.setBackground(new java.awt.Color(22, 67, 108));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(185, 45));
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDeleteMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jLabel13.setText("Delete");

        javax.swing.GroupLayout jButtonDeleteLayout = new javax.swing.GroupLayout(jButtonDelete);
        jButtonDelete.setLayout(jButtonDeleteLayout);
        jButtonDeleteLayout.setHorizontalGroup(
            jButtonDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonDeleteLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jButtonDeleteLayout.setVerticalGroup(
            jButtonDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Số điện thoại :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Địa chỉ :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Tên nhà cung cấp :");

        javax.swing.GroupLayout jPOptionsSanphamLayout = new javax.swing.GroupLayout(jPOptionsSanpham);
        jPOptionsSanpham.setLayout(jPOptionsSanphamLayout);
        jPOptionsSanphamLayout.setHorizontalGroup(
            jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPOptionsSanphamLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOptionsSanphamLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButtonChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPOptionsSanphamLayout.createSequentialGroup()
                        .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(77, 77, 77)
                        .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtAddressBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(115, 115, 115))
        );
        jPOptionsSanphamLayout.setVerticalGroup(
            jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOptionsSanphamLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPOptionsSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 227, Short.MAX_VALUE))
        );

        jTNCC.addTab("Các lựa chọn khác", jPOptionsSanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTNCC)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTNCC)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressBrand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressBrand1ActionPerformed
        
    }//GEN-LAST:event_txtAddressBrand1ActionPerformed

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        String TenNcc ,Diachi , Phone ;
        TenNcc = txtNameBrand.getText();
        Diachi = txtAddressBrand.getText();
        Phone = txtPhoneBrand.getText();
        
        String sql = "insert into Manufacturers values (N'"+TenNcc+"',N'"+Diachi+"','"+Phone+"')";
        if (TenNcc.isEmpty())
        {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên nhà cung cấp !","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        else if (Diachi.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Địa chỉ !","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        else if (Phone.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại !","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
        else {
            desktopapp.DesktopApp.connection.ExcuteQueryUpdateDB(sql);
            JOptionPane.showMessageDialog(this, "Thêm thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ClearText(txtNameBrand,txtAddressBrand,txtPhoneBrand);
            Showdata();
        }
    }//GEN-LAST:event_jButtonAddMouseClicked

    private void TableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNCCMouseClicked
        
        DefaultTableModel tableNcc  = (DefaultTableModel) TableNCC.getModel();
        
        String ID = tableNcc.getValueAt(TableNCC.getSelectedRow(),0).toString();
        String Name = tableNcc.getValueAt(TableNCC.getSelectedRow(),1).toString();
        String Address = tableNcc.getValueAt(TableNCC.getSelectedRow(), 2).toString();
        String Phone = tableNcc.getValueAt(TableNCC.getSelectedRow(), 3).toString();
        
        txtID.setText(ID);
        txtNameBrand1.setText(Name);
        txtAddressBrand1.setText(Address);
        txtPhoneBrand1.setText(Phone);
        
        jTNCC.setSelectedIndex(2);
    }//GEN-LAST:event_TableNCCMouseClicked

    private void jButtonSearcnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearcnMousePressed
        SearchKhachHang();
    }//GEN-LAST:event_jButtonSearcnMousePressed

    private void jButtonChangeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChangeMousePressed
        
        String ID ,Name , Address ,Phone ;
        ID = txtID.getText();
        Name = txtNameBrand1.getText();
        Phone = txtPhoneBrand1.getText();
        Address = txtAddressBrand1.getText();
        
        if(!ID.isEmpty())
        {
            String sql ="update Manufacturers set Name = '"+Name+"',Address = '"+Address+"' ,Phone= '"+Phone+"' where ManufacturerID = '"+ID+"'";
        
            desktopapp.DesktopApp.connection.ExcuteQueryUpdateDB(sql);
            JOptionPane.showMessageDialog(this,"Sửa thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            Showdata();
            ClearText(txtID,txtNameBrand1,txtAddressBrand1,txtPhoneBrand1);
        
            jTNCC.setSelectedIndex(1);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhà cung cấp!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonChangeMousePressed

    private void jButtonDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMousePressed
        String MaNCC = txtID.getText();
        if(!MaNCC.isEmpty())
        {
            boolean hasproduct = CheckNCC(MaNCC);
            if (!hasproduct)
            {
                String sql = "delete from Manufacturers where ManufacturerID ="+MaNCC;
                desktopapp.DesktopApp.connection.ExcuteQueryUpdateDB(sql);
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                ClearText(txtAddressBrand1,txtNameBrand1,txtPhoneBrand1,txtID);
                jTNCC.setSelectedIndex(1);
                Showdata();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Không thể xóa nhà cung cấp!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhà cung cấp!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteMousePressed

    private boolean CheckNCC(String MaNcc)
    {
        String sql = "SELECT COUNT(*) AS Count FROM Products WHERE ManufacturerID ="+MaNcc;
        int productcount = 0;
        ResultSet rs =desktopapp.DesktopApp.connection.ExcuteQueryGetTable(sql);
        try {
            if (rs.next())
            {
                productcount = rs.getInt("Count");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return productcount>0;
    }

    public static void ClearText(JTextField... textFields){
        for (JTextField textField : textFields)
        {
            textField.setText("");
        }
    }
    public void Showdata()
    {
        String sql = "select * from Manufacturers";
        ResultSet rs = desktopapp.DesktopApp.connection.ExcuteQueryGetTable(sql);
        
        DefaultTableModel tbModel = (DefaultTableModel) TableNCC.getModel();
        tbModel.setRowCount(0);
        
        Object obj[] = new Object[10];
        
        try {
            while (rs.next()) {
                obj[0] = rs.getString("ManufacturerID");
                obj[1] = rs.getString("Name");
                obj[2] = rs.getString("Address");
                obj[3] = rs.getString("Phone");
                
                tbModel.addRow(obj);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(),"Lỗi truy xuất dữ liệu ");
        }
    }
    
        public void SearchKhachHang()
    {
        String sql = "select * from Manufacturers where Name like N'%"+txtSearchNCC.getText()+"%'";
        ResultSet rs = desktopapp.DesktopApp.connection.ExcuteQueryGetTable(sql);
        
        DefaultTableModel tbModel = (DefaultTableModel) TableNCC.getModel();
        tbModel.setRowCount(0);
        
        Object obj[] = new Object[10];
        
        try {
            while (rs.next()) {
                obj[0] = rs.getString("ManufacturerID");
                obj[1] = rs.getString("Name");
                obj[2] = rs.getString("Address");
                obj[3] = rs.getString("Phone");
                
                tbModel.addRow(obj);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(),"Lỗi truy xuất dữ liệu ");
        }        
    }
    private void setJtextField(boolean a)
    {
        this.txtID.setEnabled(!a);
        this.jPOptionsSanpham.setEnabled(!a);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNCC;
    private javax.swing.JPanel jButtonAdd;
    private javax.swing.JPanel jButtonChange;
    private javax.swing.JPanel jButtonDelete;
    private javax.swing.JLabel jButtonSearcn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAddSanpham;
    private javax.swing.JPanel jPOptionsSanpham;
    private javax.swing.JPanel jPQlSanpham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTNCC;
    private javax.swing.JTextField txtAddressBrand;
    private javax.swing.JTextField txtAddressBrand1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNameBrand;
    private javax.swing.JTextField txtNameBrand1;
    private javax.swing.JTextField txtPhoneBrand;
    private javax.swing.JTextField txtPhoneBrand1;
    private javax.swing.JTextField txtSearchNCC;
    // End of variables declaration//GEN-END:variables

    private void ShowData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
